language: cpp
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y scons python-jinja2 python3
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo add-apt-repository -y ppa:mapnik/boost
 - sudo apt-get update -q
 - sudo apt-get install -y gcc-arm-none-eabi g++-5
 - sudo apt-get install -y libboost1.49-dev libboost-system1.49-dev libboost-thread1.49-dev
 - sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev
 - export CC=gcc-5
 - export CXX=g++-5

env:
 - TEST_SUITE="unittest"
 - TEST_SUITE="hardware=stm32f3_discovery"

script:
 - cd src && scons $TEST_SUITE
